{% set name = "spyder-remote-client" %}
{% set version = "0.0.3" %}
{% set hash = "6fb9b16393e0dff5cf94ff4ace5fb3789c59ba4fcad7f9140584574d1f78814c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - netifaces
    - psutil
    - python
    - zeroconf

test:
  imports:
    - spyder_remote_client

about:
  home: https://github.com/Semi-ATE/spyder-remote/tree/master/spyder-remote-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder remote client to connect to Spyder kernels via zeroconf
  description: |
    Spyder remote client to connect to Spyder kernels via zeroconf.
  doc_url: https://semi-ate.github.io/spyder-remote/
  dev_url: https://github.com/Semi-ATE/spyder-remote/

extra:
  recipe-maintainers:
    - goanpeca
    - nerohmot
