{% set name = "spyder-remote-client" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f778b39d193e2b185cb5e4922ecc3ec2b60f970cde219bb32796b552f515eb6e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - netifaces
    - psutil
    - python >={{ python_min }}
    - zeroconf

test:
  requires:
    - python {{ python_min }}
  imports:
    - spyder_remote_client

about:
  home: https://github.com/Semi-ATE/spyder-remote/tree/master/spyder-remote-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder remote client to connect to Spyder kernels via zeroconf
  description: |
    Spyder remote client to connect to Spyder kernels via zeroconf.
  doc_url: https://semi-ate.github.io/spyder-remote/
  dev_url: https://github.com/Semi-ATE/spyder-remote/

extra:
  recipe-maintainers:
    - goanpeca
    - nerohmot
